// export const baseURL = 'http://localhost:5000'
export const baseURL = 'http://backend.serveo.net'

export const loginUrl = baseURL + '/login'
export const karyawanAllUrl = baseURL + '/karyawan/all'
export const karyawanIdUrl = baseURL + '/karyawan/'
export const registerUrl = baseURL + '/registration'
export const updateUrl = baseURL + '/karyawan/update/'
export const deleteUrl = baseURL + '/karyawan/delete/'
export const createKaryawanUrl = baseURL + '/karyawan/create'